name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  linter:
    name: Ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - uses: gradle/actions/setup-gradle@v3

      - name: Create google-services.json
        shell: bash
        run: |
            mkdir -p app
            echo "${{ secrets.GOOGLE_SERVICES_JSON_B64 }}" | base64 --decode > app/google-services.json
            test -f app/google-services.json


      - name: Run ktlint
        run: ./gradlew --no-daemon ktlintCheck

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - uses: android-actions/setup-android@v3

      - uses: gradle/actions/setup-gradle@v3

      - name: Create google-services.json
        shell: bash
        run: |
            mkdir -p app
            echo "${{ secrets.GOOGLE_SERVICES_JSON_B64 }}" | base64 --decode > app/google-services.json
            test -f app/google-services.json

      - name: Run unit tests
        run: ./gradlew --no-daemon test
